Only load test results if the test finished normally but failed.

diff --git a/bin/gw b/bin/gw
--- a/bin/gw
+++ b/bin/gw
@@ -19,12 +19,18 @@ log-file() {
 
 gradle-logged() {
 	local file; file=$(log-file)
-	{
+	local status; status=$(mktemp)
+	if ! {
+		trap 'echo "interrupted" > $status' INT
 		echo gradle "$@"
 		echo "----"
 		gradle "$@" 2>&1
-	} | tee "$file" || true
-nvim +$ "$file"
+	} > >(tee "$file"); then
+		# here something has failed. only load logs if not interrupted
+		if [[ "$(cat "$status")" != "interrupted" ]]; then
+			nvim +$ "$file"
+		fi
+	fi
 }
 
 run-tests() {
